/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\all-LOW1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/all-LOW1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.water.geometry} material={materials.water} position={[-0.821, -0.286, -0.503]} rotation={[1.676, 0.279, 1.207]} scale={1.354} />
      <mesh geometry={nodes.clouds.geometry} material={materials['cloud-white']} position={[-2.662, 0.282, 0.715]} rotation={[1.525, -0.61, 1.184]} scale={0.137} />
      <mesh geometry={nodes.cross.geometry} material={materials['cross-red']} position={[-0.627, -0.481, -1.839]} rotation={[1.493, -0.666, -2.846]} scale={[0.04, 0.17, 0.17]} />
      <group position={[-0.981, 0.55, 0.613]} rotation={[1.061, -0.19, 0.059]} scale={[0.067, 0.057, 0.1]}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['house white']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['house-red']} />
      </group>
      <mesh geometry={nodes.chest.geometry} material={materials['brown-chest']} position={[-0.871, -0.66, -1.921]} rotation={[-0.895, -0.062, -1.358]} scale={[0.072, 0.085, 0.072]} />
      <mesh geometry={nodes.stone.geometry} material={materials['stone gray']} position={[-0.393, -1.549, -0.924]} rotation={[-2.032, -0.474, -1.526]} scale={0.045} />
      <mesh geometry={nodes.sun.geometry} material={materials['sun yellow']} position={[1.302, 0.547, -1.86]} scale={0.409} />
      <mesh geometry={nodes.torch.geometry} material={materials['brown-torch']} position={[-2.335, -1.103, -1.851]} rotation={[3.02, 0.041, -2.891]} scale={[0.017, 0.085, 0.026]} />
      <mesh geometry={nodes.tree.geometry} material={materials.tree} position={[-1.238, -0.654, -1.817]} rotation={[-1.574, -0.433, 0.431]} scale={0.045} />
      <group position={[-0.249, -0.048, 0.974]} rotation={[0.001, 0.941, -1.321]} scale={[0.232, 0.164, 0.074]}>
        <mesh geometry={nodes.Plane090.geometry} material={materials['plane-white']} />
        <mesh geometry={nodes.Plane090_1.geometry} material={materials['plane-red']} />
        <mesh geometry={nodes.Plane090_2.geometry} material={materials.planeBlue} />
      </group>
      <mesh geometry={nodes.land.geometry} material={materials.land} position={[-0.821, -0.286, -0.503]} rotation={[1.676, 0.279, 1.207]} scale={1.317} />
      <mesh geometry={nodes['-sample'].geometry} material={materials.planeBlue} position={[-4.179, 1.781, 3.738]} rotation={[Math.PI / 2, 0, 0]} scale={[0.49, 0.49, 0.525]} />
      <group position={[-4.809, 1.407, 3.252]} scale={0.076}>
        <mesh geometry={nodes.ComputerMouse_mesh_1.geometry} material={materials.ComputerMouse_mat1} />
        <mesh geometry={nodes.ComputerMouse_mesh_1_1.geometry} material={materials['mouse-blue']} />
      </group>
      <group position={[-3.991, 1.406, 3.291]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.008}>
        <mesh geometry={nodes.Keyboard_1.geometry} material={materials.keyboard} />
        <mesh geometry={nodes.Keyboard_1_1.geometry} material={materials['Material.004']} />
      </group>
      <mesh geometry={nodes.monitor.geometry} material={materials['mointor-blue']} position={[-4.178, 1.419, 3.821]} rotation={[0, -Math.PI / 2, 0]} scale={0.136} />
      <mesh geometry={nodes.ps4.geometry} material={materials['Material.001']} position={[-3.211, 1.765, 3.442]} rotation={[-Math.PI, 0, Math.PI / 2]} scale={0.354} />
      <mesh geometry={nodes.this_is_my_steup.geometry} material={materials['text-color']} position={[-3.273, 1.139, 2.901]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.219} />
      <group position={[-3.285, 1.504, 3.461]} rotation={[1.57, -0.451, 1.565]} scale={0.013}>
        <mesh geometry={nodes.Xbox_Controller_1.geometry} material={materials.controller} />
        <mesh geometry={nodes.Xbox_Controller_1_1.geometry} material={materials.joystick} />
      </group>
      <mesh geometry={nodes.Desk2.geometry} material={materials.Material} position={[-4.119, 1.367, 3.573]} scale={[1.123, 0.048, 0.671]} />
      <group position={[-0.586, 4.065, 4.784]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.098}>
        <mesh geometry={nodes.Text004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Text004_1.geometry} material={materials.boxblue2} />
        <mesh geometry={nodes.Text004_2.geometry} material={materials['box-blue1']} />
        <mesh geometry={nodes.Text004_3.geometry} material={materials['box-green']} />
        <mesh geometry={nodes.Text004_4.geometry} material={materials.boxgreen2} />
      </group>
      <group position={[-0.706, 4.063, 4.876]}>
        <mesh geometry={nodes.mesh660411554.geometry} material={materials.mat23} />
        <mesh geometry={nodes.mesh660411554_1.geometry} material={materials.mat16} />
        <mesh geometry={nodes.mesh660411554_2.geometry} material={materials.mat17} />
      </group>
      <group position={[-2.487, 3.899, 4.162]} rotation={[-2.037, -0.153, -1.948]}>
        <mesh geometry={nodes['bodyMesh001_lowman_toes030-Mesh'].geometry} material={materials['sculpture.002']} />
        <mesh geometry={nodes['bodyMesh001_lowman_toes030-Mesh_1'].geometry} material={materials.arm1} />
        <mesh geometry={nodes['bodyMesh001_lowman_toes030-Mesh_2'].geometry} material={materials.arm2} />
      </group>
    </group>
  )
}

useGLTF.preload('/all-LOW1.glb')
